using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.XR;
using UnityEngine.XR.Interaction.Toolkit;

public class Syringe : MonoBehaviour
{
    public GameObject[] Dots;

    private void Awake()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }

    public void Dot_1()
    {
        Dots[0].SetActive(true);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_2()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(true);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_3()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(true);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_4()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(true);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_5()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(true);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_6()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(true);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_7()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(true);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_8()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(true);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_9()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(true);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_10()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(true);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_11()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(true);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_12()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(true);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }
    public void Dot_13()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(true);
        Dots[13].SetActive(false);
        Dots[14].SetActive(false);
    }

    public void Dot_14()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(true);
        Dots[14].SetActive(false);
    }

    public void Dot_15()
    {
        Dots[0].SetActive(false);
        Dots[1].SetActive(false);
        Dots[2].SetActive(false);
        Dots[3].SetActive(false);
        Dots[4].SetActive(false);
        Dots[5].SetActive(false);
        Dots[6].SetActive(false);
        Dots[7].SetActive(false);
        Dots[8].SetActive(false);
        Dots[9].SetActive(false);
        Dots[10].SetActive(false);
        Dots[11].SetActive(false);
        Dots[12].SetActive(false);
        Dots[13].SetActive(false);
        Dots[14].SetActive(true);
    }
}
